name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - { platform: "x64"}
        - { platform: "Win32"}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: cmake -DCMAKE_C_FLAGS_RELEASE="/MT /O2" -A ${{matrix.config.platform}} -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release -j
